# basic options
title: Your awesome title
author: GitHub User
email: ashay17awalke@gmail.com  
description: A wonderful site
twitter_username: jekyllrb
github_username:  ashaywalke

# Build settings
markdown: kramdown
theme: minima
